package com.andersenlab;
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultSuiteTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeClass
    public static void setDriver() {
        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chromedriver.exe");
    }

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testcase1() {
        // Test name: Test-case 1
        // Step # | name | target | value
        // 1 | executeScript | return Math.random().toString(36).substring(2,12) | name
        // Генерируем случайное имя
        vars.put("name", js.executeScript("return Math.random().toString(36).substring(2,12)"));
        // 2 | open | /user/login |
        // Открыть окно браузера
        driver.get("https://crm.geekbrains.space/user/login");
        // 3 | setWindowSize | 1552x840 |
        // Увеличить окно браузера
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 4 | type | id=prependedInput |  Applanatest1
        // Ввести логин
        driver.findElement(By.id("prependedInput")).sendKeys(" Applanatest1");
        // 5 | click | id=prependedInput2 |
        // Установить курсор на поле ввода "Пароль"
        driver.findElement(By.id("prependedInput2")).click();
        // 6 | type | id=prependedInput2 | Student2020!
        // Ввести пароль
        driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
        // 7 | click | id=remember_me |
        // Установить флажок "Запомнить меня на этом компьютере"
        driver.findElement(By.id("remember_me")).click();
        // 8 | click | id=_submit |
        // Нажать "Войти"
        driver.findElement(By.id("_submit")).click();
        // 9 | waitForElementNotVisible | id=progressbar | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("progressbar")));
        }
        // 10 | assertElementPresent | linkText=Проекты |
        // Элемент "Проекты" должен находиться на странице
        {
            List<WebElement> elements = driver.findElements(By.linkText("Проекты"));
            assert (elements.size() > 0);
        }
        // 11 | mouseOver | linkText=Проекты |
        // Навести курсор мыши на "Проекты"
        {
            WebElement element = driver.findElement(By.linkText("Проекты"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 12 | waitForElementVisible | css=.dropdown:nth-child(3) > ul > li:nth-child(4) | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".dropdown:nth-child(3) > ul > li:nth-child(4)")));
        }
        // 13 | click | css=.dropdown:nth-child(3) > ul > li:nth-child(4) > a |
        // Выбрать "Мои проекты"
        driver.findElement(By.cssSelector(".dropdown:nth-child(3) > ul > li:nth-child(4) > a")).click();
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Создать проект")));
        }
        // 14 | click | linkText=Создать проект |
        // Нажать "Создать проект"
        driver.findElement(By.linkText("Создать проект")).click();
        // 15 | waitForElementVisible | css=.controls > input[data-ftid=crm_project_name] | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".controls > input[data-ftid=crm_project_name]")));
        }
        // 16 | click | css=.controls > input[data-ftid=crm_project_name] |
        // Установить курсор в поле "Наименование"
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_project_name]")).click();
        // 17 | type | css=.controls > input[data-ftid=crm_project_name] | ${name}
        // Указать наименование
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_project_name]")).sendKeys(vars.get("name").toString());
        // 18 | click | css=.select2-default > .select2-chosen |
        // Установить курсор в поле "Организация"
        driver.findElement(By.cssSelector(".select2-default > .select2-chosen")).click();
        // 19 | waitForElementPresent | css=.select2-with-searchbox > .select2-results > li:last-child | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".select2-results > li:nth-child(1) > .select2-result-label")));
        }
        // Кликнуть на выпадающий список
        driver.findElement(By.cssSelector(".select2-results > li:nth-child(1) > .select2-result-label")).click();
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//select[@data-ftid='crm_project_contactMain']")));
        }
        // Кликнуть на выпадающий список
        driver.findElement(By.xpath("//div[@class='controls']/div[@class='select2-container select2']/a[@class='select2-choice']/span[@class='select2-arrow']")).click();
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".select2-highlighted")));
        }
        // Выбрать из списка контакное лицо
        driver.findElement(By.cssSelector(".select2-highlighted")).click();

        // 30 | click | css=select[data-ftid=crm_project_businessUnit] |
        // Установить курсор в поле "Подразделение"
        driver.findElement(By.cssSelector("select[data-ftid=crm_project_businessUnit]")).click();
        // 31 | select | css=select[data-ftid=crm_project_businessUnit] | label=Research & Development
        // Выбрать из списка подразделение
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_project_businessUnit]"));
            dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
        }
        // 32 | click | css=select[data-ftid=crm_project_curator] |
        // Установить курсор в поле "Куратор проекта"
        driver.findElement(By.cssSelector("select[data-ftid=crm_project_curator]")).click();
        // 33 | select | css=select[data-ftid=crm_project_curator] | label=Юзеров Юзер
        // Выбрать из списка куратора проекта
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_project_curator]"));
            dropdown.findElement(By.xpath("//option[. = 'Юзеров Юзер']")).click();
        }
        // 34 | click | css=select[data-ftid=crm_project_rp] |
        // Установить курсор в поле "Руководитель проекта"
        driver.findElement(By.cssSelector("select[data-ftid=crm_project_rp]")).click();
        // 35 | select | css=select[data-ftid=crm_project_rp] | label=Катков Александр
        // Выбрать из списка руководителя проекта
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_project_rp]"));
            dropdown.findElement(By.xpath("//option[. = 'Катков Александр']")).click();
        }
        // 36 | click | css=select[data-ftid=crm_project_administrator] |
        // Установить курсор в поле "Администратор проекта"
        driver.findElement(By.cssSelector("select[data-ftid=crm_project_administrator]")).click();
        // 37 | select | css=select[data-ftid=crm_project_administrator] | label=Ямутина Вера
        // Выбрать из списка администратора проекта
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_project_administrator]"));
            dropdown.findElement(By.xpath("//option[. = 'Ямутина Вера']")).click();
        }
        // 38 | click | css=select[data-ftid=crm_project_manager] |
        // Установить курсор в поле "Менеджер"
        driver.findElement(By.cssSelector("select[data-ftid=crm_project_manager]")).click();
        // 39 | select | css=select[data-ftid=crm_project_manager] | label=Прохорова Екатерина
        // Выбрать из списка менеджера
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_project_manager]"));
            dropdown.findElement(By.xpath("//option[. = 'Прохорова Екатерина']")).click();
        }
        // 40 | click | css=.btn-group:nth-child(4) > .btn |
        // Нажать "Сохранить и закрыть"
        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
        // Навести курсор на выпадающее меню личного кабинета
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".loader-overlay")));
        }
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".icon-sort-down")));
        }
        driver.findElement(By.cssSelector(".icon-sort-down")).click();
        // 42 | click | css=.last > a |
        // Нажать "Выйти"
        driver.findElement(By.cssSelector(".last > a")).click();
        // 43 | close |  |
        // Закрыть окно браузера
        driver.close();
    }

    @Test
    public void testcase2() {
        // Test name: Test-case 2
        // Step # | name | target | value
        // 1 | open | https://crm.geekbrains.space/user/login |
        // Открыть окно браузера
        driver.get("https://crm.geekbrains.space/user/login");
        // 2 | setWindowSize | 1552x840 |
        // Увеличить окно браузера
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 3 | click | id=prependedInput |
        // Установить курсор на поле ввода "Имя пользователя или Email"
        driver.findElement(By.id("prependedInput")).click();
        // 4 | type | id=prependedInput | Applanatest1
        // Ввести логин
        driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
        // 5 | click | id=prependedInput2 |
        // Установить курсор на поле ввода "Пароль"
        driver.findElement(By.id("prependedInput2")).click();
        // 6 | type | id=prependedInput2 | Student2020!
        // Ввести пароль
        driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
        // 7 | click | id=remember_me |
        // Установить флажок "Запомнить меня на этом компьютере"
        driver.findElement(By.id("remember_me")).click();
        // 8 | click | id=_submit |
        // Нажать "Войти"
        driver.findElement(By.id("_submit")).click();
        // 9 | waitForElementNotVisible | id=progressbar | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.invisibilityOfElementLocated(By.id("progressbar")));
        }
        // 10 | assertElementPresent | linkText=Контрагенты |
        // Меню "Контрагенты" должно присутствовать на странице
        {
            List<WebElement> elements = driver.findElements(By.linkText("Контрагенты"));
            assert (elements.size() > 0);
        }
        // 11 | mouseOver | linkText=Контрагенты |
        // Навести курсор на меню "Контрагенты"
        {
            WebElement element = driver.findElement(By.linkText("Контрагенты"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 12 | click | css=.first .last .title |
        // Выбрать "Контактные лица"
        driver.findElement(By.cssSelector(".first .last .title")).click();
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Создать контактное лицо")));
        }

        // 13 | click | linkText=Создать контактное лицо |
        // Нажать "Создать контактное лицо"
        driver.findElement(By.linkText("Создать контактное лицо")).click();
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".controls > input[data-ftid=crm_contact_lastName]")));
        }

        // 14 | click | css=.controls > input[data-ftid=crm_contact_lastName] |
        // Установить курсор в поле "Фамилия"
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_lastName]")).click();
        // 15 | type | css=.controls > input[data-ftid=crm_contact_lastName] | Иванов
        // Указать фамилию
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_lastName]")).sendKeys("Иванов");
        // 16 | click | css=.controls > input[data-ftid=crm_contact_firstName] |
        // Установить курсор в поле "Имя"
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_firstName]")).click();
        // 17 | type | css=.controls > input[data-ftid=crm_contact_firstName] | Иван
        // Указать имя
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_firstName]")).sendKeys("Иван");
        // 18 | click | css=.controls > input[data-ftid=crm_contact_middleName] |
        // Установить курсор в поле "Отчество"
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_middleName]")).click();
        // 19 | type | css=.controls > input[data-ftid=crm_contact_middleName] | Иваныч
        // Указать отчество
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_middleName]")).sendKeys("Иваныч");
        // 20 | click | css=.select2-default > .select2-chosen  |
        // Установить курсор в поле "Организация"
        driver.findElement(By.cssSelector(".select2-default > .select2-chosen ")).click();
        // 21 | waitForElementPresent | css=.select2-with-searchbox > .select2-results > .select2-more-results | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".select2-with-searchbox > .select2-results > .select2-more-results")));
        }
        // 22 | clickAt | css=.select2-highlighted |
        // Выбрать из списка организацию
        driver.findElement(By.cssSelector(".select2-highlighted")).click();
        // 23 | click | css=.controls > input[data-ftid=crm_contact_jobTitle] |
        // Установить курсор в поле "Должность"
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_jobTitle]")).click();
        // 24 | type | css=.controls > input[data-ftid=crm_contact_jobTitle] | водитель
        // Указать должность
        driver.findElement(By.cssSelector(".controls > input[data-ftid=crm_contact_jobTitle]")).sendKeys("водитель");
        // 25 | click | css=select[data-ftid=crm_contact_status] |
        // Установить курсор в поле "Статус"
        driver.findElement(By.cssSelector("select[data-ftid=crm_contact_status]")).click();
        // 26 | select | css=select[data-ftid=crm_contact_status] | label=Активный
        // Выбрать из списка статус
        {
            WebElement dropdown = driver.findElement(By.cssSelector("select[data-ftid=crm_contact_status]"));
            dropdown.findElement(By.xpath("//option[. = 'Активный']")).click();
        }
        // 27 | click | css=.btn-group:nth-child(4) > .btn |
        // Нажать "Сохранить и закрыть"
        driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
        // 28 | waitForElementNotVisible | css=.loader-overlay | 30000
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector(".loader-overlay")));
        }
        // Ожидание загрузки
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".icon-sort-down")));
        }
        // 29 | click | css=.icon-sort-down |
        // Навести курсор на выпадающее меню личного кабинета
        driver.findElement(By.cssSelector(".icon-sort-down")).click();
        // 30 | click | css= .last > a |
        // Нажать "Выйти"
        driver.findElement(By.cssSelector(" .last > a")).click();
        // 31 | close |  |
        // Закрыть окно браузера
        driver.close();
    }
}
