package com.andersenlab;
// Generated by Selenium IDE

import org.junit.*;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import java.util.stream.IntStream;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Lesson11Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeClass
    public static void setDriver() {
        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chromedriver.exe");
    }

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void authorization() {
        // Test name: Authorization
        // Step # | name | target | value
        // 1 | open | https://diary.ru/ |
        // Открыть окно браузера
        driver.get("https://diary.ru/");
        // 2 | setWindowSize | 1552x840 |
        // Увеличить размер окна браузера
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 3 | click | linkText=Вход |
        // Нажать "Вход"
        driver.findElement(By.linkText("Вход")).click();
        // 4 | mouseOver | linkText=Вход |
        // Навести курсор мыши на поле авторизации
        {
            WebElement element = driver.findElement(By.linkText("Вход"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 5 | mouseOut | linkText=Вход |
        // Установить курсор мыши для ввода данных
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 6 | click | id=loginform-password |
        // Ввести логин и пароль
        driver.findElement(By.id("loginform-username")).sendKeys("Irararira");

        driver.findElement(By.id("loginform-password")).sendKeys("Qwer123");
        // 7 | selectFrame | index=0 |
        // Установить фложок "Запомнить"
        driver.switchTo().frame(0);
        // 8 | click | css=.recaptcha-checkbox-border |
        // Установить флажок "Я не робот"
        driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
        // 9 | selectFrame | relative=parent |
        // Выбрать парентовый фрейм
        driver.switchTo().defaultContent();
        // 10 | click | id=login_btn |
        // Нажать "Войти"
        driver.findElement(By.id("login_btn")).click();
        // Ожидание загрузки элемента
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Irararira")));
        }

        // 11 | click | linkText=Irararira |
        // Вход в личный кабинет
        driver.findElement(By.linkText("Irararira")).click();
        // 12 | waitForElementVisible | css=.grey | 30000
        // Ожидание загрузки элемента
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".grey")));
        }
        // 13 | click | id=drop_right_menu |
        // Нажать "Мое меню"
        driver.findElement(By.id("drop_right_menu")).click();
        // 14 | click | linkText=Выход |
        // Нажать "Выход"
        driver.findElement(By.linkText("Выход")).click();
        // 15 | close |  |
        // Закрыть окно браузера
        driver.close();
    }

    @Test
    public void newentry() throws InterruptedException {
        // Открыть окно браузера
        driver.get("https://diary.ru/");
        Cookie _csrf = new Cookie("_csrf", "2d5890af3e657b5b38b99b4c48dc121a26585d98792aee88fb49d4402f926840a%3A2%3A%7Bi%3A0%3Bs%3A10%3A%22_identity_%22%3Bi%3A1%3Bs%3A52%3A%22%5B3552238%2C%22JuVQDRG-v6prtZfcWVV7MOtqVQn2Eh-x%22%2C2592000%5D%22%3B%7D");
        Cookie _session = new Cookie("_session", "lkt1uua8p4087blm45jp8jg9m8");
        Cookie _identity = new Cookie("_identity_", "2d5890af3e657b5b38b99b4c48dc121a26585d98792aee88fb49d4402f926840a%3A2%3A%7Bi%3A0%3Bs%3A10%3A%22_identity_%22%3Bi%3A1%3Bs%3A52%3A%22%5B3552238%2C%22JuVQDRG-v6prtZfcWVV7MOtqVQn2Eh-x%22%2C2592000%5D%22%3B%7D");
        driver.manage().addCookie(_csrf);
        driver.manage().addCookie(_session);
        driver.manage().addCookie(_identity);
        // 2 | setWindowSize | 1552x840 |
        // Увеличить размер окна браузера
        driver.manage().window().setSize(new Dimension(1552, 840));
        driver.findElement(By.linkText("Вход")).click();
        // Ожидание загрузки элемента
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("a > .i-menu-newpost")));
        }
        // 3 | click | css=a > .i-menu-newpost |
        // Нажать "Новая запись"
        driver.findElement(By.cssSelector("a > .i-menu-newpost")).click();
        // 4 | click | id=postTitle |
        // Установить курсор мыши в поле "Заголовок:"
        driver.findElement(By.id("postTitle")).click();
        // 5 | type | id=postTitle | Путешествие во Львов
        // Ввести заголовок
        driver.findElement(By.id("postTitle")).sendKeys("Путешествие во Львов");
        // 6 | click | id=postTitle |
        // Установить курсор мыши в поле "Сообщение:"
        driver.findElement(By.id("postTitle")).click();
        // 7 | runScript | window.scrollTo(0,200) |
        // Прокрутка окна
        js.executeScript("window.scrollTo(0,200)");
        // 8 | selectFrame | index=1 |
        // Начало ввода текста в поле "Сообщение:"
        driver.switchTo().frame(2);
        // Ожидание загрузки элемента
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//html/body")));
        }
        // Ввод текста
        driver.findElement(By.xpath("//html/body")).sendKeys("Львов потрясающе красивый город со множеством достопримечательностей.");
        // 11 | selectFrame | relative=parent |
        // Нажать "Сохранить черновик"
        driver.switchTo().defaultContent();
        // 12 | click | linkText=Irararira |
        // Перейти в личный кабинет
        driver.findElement(By.linkText("Irararira")).click();
        // 13 | click | id=drop_right_menu |
        // Нажать "Мое меню"
        driver.findElement(By.id("drop_right_menu")).click();
        // 14 | click | linkText=Черновики |
        // Нажать "Черновики"
        driver.findElement(By.linkText("Черновики")).click();
        // 15 | click | css=.draft_prview_link > span |
        // Предпросмотр черновика
        driver.findElement(By.cssSelector(".draft_prview_link > span")).click();
        // 16 | close |  |
        // Закрыть окно браузера
        driver.close();
    }
}
