package com.andersenlab;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class QuickstartTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

//    @BeforeClass
//    public static void setDriver() {
//        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver\\chromedriver.exe");
//    }

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void quickstart() {
        // Test name: quickstart
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.ukr.net/");
        // 2 | setWindowSize | 1552x840 |
        driver.manage().window().setSize(new Dimension(1552, 840));
        // 3 | selectFrame | index=0 |
        driver.switchTo().frame(0);
        // 4 | click | id=id-input-login |
        driver.findElement(By.id("id-input-login")).click();
        // 5 | type | id=id-input-login | irsanchik@tut.by
        driver.findElement(By.id("id-input-login")).sendKeys("irsanchik@tut.by");
        // 6 | verifyValue | id=id-input-login | irsanchik@tut.by
        {
            String value = driver.findElement(By.id("id-input-login")).getAttribute("value");
            assertThat(value, is("irsanchik@tut.by"));
        }
        // 7 | click | id=id-input-password |
        driver.findElement(By.id("id-input-password")).click();
        // 8 | type | id=id-input-password | Qwer123
        driver.findElement(By.id("id-input-password")).sendKeys("Qwer123");
        // 9 | verifyValue | id=id-input-password | Qwer123
        {
            String value = driver.findElement(By.id("id-input-password")).getAttribute("value");
            assertThat(value, is("Qwer123"));
        }
        // 10 | click | css=.form__checkbox-label |
        driver.findElement(By.cssSelector(".form__checkbox-label")).click();
        // 11 | close |  |
        driver.close();
    }

}
